@Backend_HostAddress = http://localhost:5144

GET {{Backend_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Backend_HostAddress}}/api/korisnik
Accept: application/json

###
GET {{Backend_HostAddress}}/api/korisnik/
Accept: application/json

###
POST {{Backend_HostAddress}}/api/korisnik
Content-Type: application/json

{
  "ime": "MIRZA",
  "prezime": "HODZIC",
  "radnoMjesto": "Veterinar",
  "korisnickoIme": "hodzicmirza",
  "hashLozinke": "hodzicmirza",
  "telefon": "+38762075029",
  "email": "hodzic04mirza@gmail.com",
  "datumZaposlenja": "2025-12-14",
  "odjel": "Farmer",         
  "statusNaloga": "Aktivan", 
  "napomene": "Napomena"
}

