// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(SmartCowFarmDatabaseContext))]
    [Migration("20251214142832_InicijalnaMigracija")]
    partial class InicijalnaMigracija
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Korisnik", b =>
                {
                    b.Property<int>("IdKorisnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdKorisnika"));

                    b.Property<DateOnly>("DatumZaposlenja")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashLozinke")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Napomene")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Odjel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RadnoMjesto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusNaloga")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdKorisnika");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("Backend.Models.Krava", b =>
                {
                    b.Property<int>("IdKrave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdKrave"));

                    b.Property<DateOnly>("DatumDolaska")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<int?>("IdMajke")
                        .HasColumnType("integer");

                    b.Property<int?>("MajkaKravaIdKrave")
                        .HasColumnType("integer");

                    b.Property<string>("Napomene")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpisIzgleda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OznakaKrave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PocetnaTezina")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("PorijekloTip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProsjecnaDnevnaProizvodnjaL")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Rasa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TrenutnaProcijenjenaTezina")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TrenutniStatus")
                        .HasColumnType("integer");

                    b.HasKey("IdKrave");

                    b.HasIndex("MajkaKravaIdKrave");

                    b.ToTable("Krave");
                });

            modelBuilder.Entity("Backend.Models.Muza", b =>
                {
                    b.Property<int>("IdMuze")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMuze"));

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("IdKrave")
                        .HasColumnType("integer");

                    b.Property<decimal>("KolicinaLitara")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("NacinUnosa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OznakaOdstupanja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProsjecanProtokLMin")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TemperaturaMlijeka")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<TimeOnly>("VrijemePocetka")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("VrijemeZavrsretka")
                        .HasColumnType("time without time zone");

                    b.HasKey("IdMuze");

                    b.HasIndex("IdKrave");

                    b.ToTable("Muze");
                });

            modelBuilder.Entity("Backend.Models.OcitanjeSenzora", b =>
                {
                    b.Property<int>("IdOcitanja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOcitanja"));

                    b.Property<int?>("IdOsobeReagovala")
                        .HasColumnType("integer");

                    b.Property<int>("IdSenzora")
                        .HasColumnType("integer");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusOcitanja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Vrijednost")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.HasKey("IdOcitanja");

                    b.HasIndex("IdSenzora");

                    b.ToTable("OcitanjaSenzora");
                });

            modelBuilder.Entity("Backend.Models.Senzor", b =>
                {
                    b.Property<int>("IdSenzora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSenzora"));

                    b.Property<DateOnly>("DatumKalibracije")
                        .HasColumnType("date");

                    b.Property<string>("JedinicaMjere")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PragCriticalMax")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal>("PragCriticalMin")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal>("PragNormalnoMax")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal>("PragNormalnoMin")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TipSenzora")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdSenzora");

                    b.ToTable("Senzori");
                });

            modelBuilder.Entity("Backend.Models.Terapija", b =>
                {
                    b.Property<int>("IdTerapije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTerapije"));

                    b.Property<DateOnly>("DatumKraja")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DatumPocetka")
                        .HasColumnType("date");

                    b.Property<decimal>("Doza")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("IdSlucaja")
                        .HasColumnType("integer");

                    b.Property<string>("JedinicaMjere")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NazivLijeka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrajanjeDana")
                        .HasColumnType("integer");

                    b.Property<string>("Ucestalost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uputstvo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZdravstveniSlucajIdSlucaja")
                        .HasColumnType("integer");

                    b.HasKey("IdTerapije");

                    b.HasIndex("ZdravstveniSlucajIdSlucaja");

                    b.ToTable("Terapije");
                });

            modelBuilder.Entity("Backend.Models.TerapijaAplikacije", b =>
                {
                    b.Property<int>("IdAplikacije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAplikacije"));

                    b.Property<DateTime>("DatumVrijeme")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdIzvrsilac")
                        .HasColumnType("integer");

                    b.Property<int>("IdTerapije")
                        .HasColumnType("integer");

                    b.Property<int>("IzvrsilacIdKorisnika")
                        .HasColumnType("integer");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrimijenjenaKolicina")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("IdAplikacije");

                    b.HasIndex("IdTerapije");

                    b.HasIndex("IzvrsilacIdKorisnika");

                    b.ToTable("TerapijeAplikacije");
                });

            modelBuilder.Entity("Backend.Models.Upozorenje", b =>
                {
                    b.Property<int>("IdUpozorenja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUpozorenja"));

                    b.Property<int?>("IdKrave")
                        .HasColumnType("integer");

                    b.Property<int?>("IdOsobaPreuzela")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSenzora")
                        .HasColumnType("integer");

                    b.Property<int?>("IdZadatka")
                        .HasColumnType("integer");

                    b.Property<string>("KanaliSlani")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NivoUpozorenja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazlogAktiviranja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusUpozorenja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipUpozorenja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VrijemeDetekcije")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VrijemePrveReakcije")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdUpozorenja");

                    b.HasIndex("IdKrave");

                    b.HasIndex("IdSenzora");

                    b.HasIndex("IdZadatka");

                    b.ToTable("Upozorenja");
                });

            modelBuilder.Entity("Backend.Models.Zadatak", b =>
                {
                    b.Property<int>("IdZadatka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdZadatka"));

                    b.Property<int?>("IdIzvrsilac")
                        .HasColumnType("integer");

                    b.Property<int?>("IdKrave")
                        .HasColumnType("integer");

                    b.Property<int>("IdKreator")
                        .HasColumnType("integer");

                    b.Property<string>("Izvor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IzvrsilacIdKorisnika")
                        .HasColumnType("integer");

                    b.Property<int?>("KravaIdKrave")
                        .HasColumnType("integer");

                    b.Property<int>("KreatorIdKorisnika")
                        .HasColumnType("integer");

                    b.Property<string>("Napomene")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NazivZadatka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioritet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RokIzvrsenja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusZadatka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipZadatka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UtroseniResursiOpis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VrijemePocetka")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VrijemeZavrsEtka")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdZadatka");

                    b.HasIndex("IzvrsilacIdKorisnika");

                    b.HasIndex("KravaIdKrave");

                    b.HasIndex("KreatorIdKorisnika");

                    b.ToTable("Zadaci");
                });

            modelBuilder.Entity("Backend.Models.ZdravstveniSlucaj", b =>
                {
                    b.Property<int>("IdSlucaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSlucaja"));

                    b.Property<string>("AiNivoRizika")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiTipAnomalije")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DatumOtvaranja")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DatumZatvaranja")
                        .HasColumnType("date");

                    b.Property<string>("Dijagnoza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdKrave")
                        .HasColumnType("integer");

                    b.Property<int?>("IdVeterinara")
                        .HasColumnType("integer");

                    b.Property<int>("KravaIdKrave")
                        .HasColumnType("integer");

                    b.Property<string>("Napomene")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpisSimptoma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazlogOtvaranja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusSlucaja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VeterinarIdKorisnika")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("VrijemeOtvaranja")
                        .HasColumnType("time without time zone");

                    b.HasKey("IdSlucaja");

                    b.HasIndex("KravaIdKrave");

                    b.HasIndex("VeterinarIdKorisnika");

                    b.ToTable("ZdravstveniSlucajevi");
                });

            modelBuilder.Entity("Backend.Models.Krava", b =>
                {
                    b.HasOne("Backend.Models.Krava", "MajkaKrava")
                        .WithMany()
                        .HasForeignKey("MajkaKravaIdKrave");

                    b.Navigation("MajkaKrava");
                });

            modelBuilder.Entity("Backend.Models.Muza", b =>
                {
                    b.HasOne("Backend.Models.Krava", "Krava")
                        .WithMany()
                        .HasForeignKey("IdKrave")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Krava");
                });

            modelBuilder.Entity("Backend.Models.OcitanjeSenzora", b =>
                {
                    b.HasOne("Backend.Models.Senzor", "Senzor")
                        .WithMany()
                        .HasForeignKey("IdSenzora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Senzor");
                });

            modelBuilder.Entity("Backend.Models.Terapija", b =>
                {
                    b.HasOne("Backend.Models.ZdravstveniSlucaj", "ZdravstveniSlucaj")
                        .WithMany()
                        .HasForeignKey("ZdravstveniSlucajIdSlucaja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZdravstveniSlucaj");
                });

            modelBuilder.Entity("Backend.Models.TerapijaAplikacije", b =>
                {
                    b.HasOne("Backend.Models.Terapija", "Terapija")
                        .WithMany()
                        .HasForeignKey("IdTerapije")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Korisnik", "Izvrsilac")
                        .WithMany()
                        .HasForeignKey("IzvrsilacIdKorisnika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izvrsilac");

                    b.Navigation("Terapija");
                });

            modelBuilder.Entity("Backend.Models.Upozorenje", b =>
                {
                    b.HasOne("Backend.Models.Krava", "Krava")
                        .WithMany()
                        .HasForeignKey("IdKrave");

                    b.HasOne("Backend.Models.Senzor", "Senzor")
                        .WithMany()
                        .HasForeignKey("IdSenzora");

                    b.HasOne("Backend.Models.Zadatak", "Zadatak")
                        .WithMany()
                        .HasForeignKey("IdZadatka");

                    b.Navigation("Krava");

                    b.Navigation("Senzor");

                    b.Navigation("Zadatak");
                });

            modelBuilder.Entity("Backend.Models.Zadatak", b =>
                {
                    b.HasOne("Backend.Models.Korisnik", "Izvrsilac")
                        .WithMany()
                        .HasForeignKey("IzvrsilacIdKorisnika");

                    b.HasOne("Backend.Models.Krava", "Krava")
                        .WithMany()
                        .HasForeignKey("KravaIdKrave");

                    b.HasOne("Backend.Models.Korisnik", "Kreator")
                        .WithMany()
                        .HasForeignKey("KreatorIdKorisnika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izvrsilac");

                    b.Navigation("Krava");

                    b.Navigation("Kreator");
                });

            modelBuilder.Entity("Backend.Models.ZdravstveniSlucaj", b =>
                {
                    b.HasOne("Backend.Models.Krava", "Krava")
                        .WithMany()
                        .HasForeignKey("KravaIdKrave")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Korisnik", "Veterinar")
                        .WithMany()
                        .HasForeignKey("VeterinarIdKorisnika");

                    b.Navigation("Krava");

                    b.Navigation("Veterinar");
                });
#pragma warning restore 612, 618
        }
    }
}
